# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  datetest:
    name: Calculate the current difference between expiration date and current date in hours
    runs-on: ubuntu-latest

    steps:
      - name: Set current date as env variable
        run: echo "NOW=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
      - name: Echo current date
        run: echo $NOW
      - name: Get repository predefined expiry date variable
        run: echo ${{ vars.EXPIRYDATE }}
      - name: Calculate diff in hours between the date values
        run: |
          echo "DIFF_HOUR=$(( ($(date -d ${{ vars.EXPIRYDATE }} +%s) - $(date -d ${{ env.NOW }} +%s) ) / 3600 ))" >> $GITHUB_ENV
      - name: Echo DIFF
        run: echo $DIFF_HOUR

  checkdate:
    name: Checks the date diff with an condition
    runs-on: ubuntu-latest

    steps:
      - name: Use Variable
        run: echo "${{ env.DIFF_HOUR }}"

    
