# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  datetest:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Set current date as env variable
        run: echo "NOW=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
      - name: Echo current date
        run: echo $NOW
      - name: get repo env date var
        run: echo ${{ vars.EXPIRYDATE }}
      - name: Test
        run: |
          echo "difference_in_hours=$(( ( $(date +%s) - $(date -d ${{ github.event.pull_request.created_at }} +%s) ) / 3600 ))" >>  "$GITHUB_OUTPUT"
    
